spring:
  application:
    name: base-service
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #Swagger需要的配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
server:
  port: 9001